### ISSUE TITLE
Ajuste asignacion_espacio_fisico_dependencia para traer datos relacionados

### ISSUE THREAD

**Issue by mariaortiz0401** [udistrital/oikos_api#28]

**Comment by mafeave** [comment]
Se verifica la carga de datos relacionados al acceder a la consulta de asignacion_espacio_fisico_dependencia
![Captura de pantalla de 2019-11-28 12-01-48](https://user-images.githubusercontent.com/14035745/69823455-e9b75080-11d6-11ea-994c-1648f5874c4d.png)

Para la carga de información relacionada de los espacios físicos, se debe hacer mediante el método GetAll del controlador
