### ISSUE TITLE
Desarrollo de versión actualizada de árbol de dependencias

### ISSUE THREAD

**Issue by faparraf** [udistrital/oikos_api#4]
Con el fin de dar cumplimiento a las necesidades expuestas por proyectos de la organización respecto a los datos contenidos en los esquemas de **OIKOS**, es necesario realizar una revisión de el árbol de dependencias que hay actualmente y de ser necesario realizar las correcciones indicadas.
**Entregables:**
- [x] Script con árbol de dependencias actualizado (de ser necesario)
- [x] Documento de justificación de cambios (justificación si no se hace ningún cambio)

**Comment by mariaortiz0401** [comment]
Debido a los cambios de contraseña de base de datos en los ambientes test, los APIs no están respondiendo correctamente, por lo que se debe corregir esto para poderse conectar y realizar las correciones del árbol de dependencias.  Esto también afectó los APIs de parametros_gobierno e idiomas.

**Comment by mariaortiz0401** [comment]
No se hace necesario script de SQL ya que la modificación de las funciones de dependencias se realizaron a nivel de código y no a nivel de base de datos.
