### ISSUE TITLE
Ajustes en el Api de Oikos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/oikos_api#44]
- [x] Descargar el repo de oikos_api y ejecutarlo en el local
- [x] Trabajar sobre la rama fixv1Controllers
- [x] En local con la VPN y utilizando las credenciales proporcionadas por los DBAs, probar apuntando a pruebas desde el local que los endpoints /v1 retornen las respuestas que actualmente está retornando en producción oikos v1.
- [x] De igual manera probar que los endpoints con /v2 retornen las respuestas que se manejan en ARKA.
- [x] Corregir endpoints personalizados.
- [x] Corregir el procesamiento de respuestas vacías de enpoints oikos v2 GET?query=..., con base en lo aplicado en el mid o cliente de arka y en el último commit https://github.com/udistrital/oikos_api/commit/ea4b6ef4851fe8cfc6a37015678c2012f7ddb0a3
- [x] Solicitud de recursos (infraestructura, dbas, juan pablo y comentarle a Jhon)
- [x] Sincronización de datos
- [x] Cambio de variables de entorno
- [x] Aplicar PR a release
- [x] Pr a dev

**Comment by ludwinggsanchez** [comment]
Comentarios generales

dependencia_padre

ArbolDependencias: OK
Facultades: OK
TRDependenciaPadre: OK

espacio_fisico

EspaciosHuerfanos: OK - ajustado
get_espacios_fisicos_hijos_by_id: OK ****No funciona en prod
get_espacios_fisicos_padres_by_id: OK ****No funciona en prod

dependencia:

proyectosPorFacultad/:id_facultad/:nivel_academico: OK
proyectosPorFacultad/:id_facultad: OK
get_dependencias_hijas_by_id/:dependencia: OK ****No funciona en prod
get_dependencias_padres_by_id/:dependencia: OK ****No funciona en prod
