### ISSUE TITLE
Revisión de modelo de base de datos de OIKOS

### ISSUE THREAD

**Issue by AlaskaRising** [udistrital/oikos_api#5]
- [x] Nueva versión de script de base de datos de OIKOS 
- [x] Revisión y aprobación de equipo ARKA, 
- [x] Revisión y aprobación de equipo arquitectura y DBAs

**Comment by mafeave** [comment]
Se valida el modelo propuesto de OIKOS, aplica para los requerimientos necesarios de los sistemas ARKA y SGA. Tener en cuenta que también se requiere consumir la información de la tabla "asignacion_espacio_fisico_dependencia" la cual no contiene datos actualmente.

**Comment by nodier25** [comment]
Se valida el modelo para la bases de datos para oikos y queda aprobado
