### ISSUE TITLE
Pruebas sobre peticiones REST versionadas 

### ISSUE THREAD

**Issue by AlaskaRising** [udistrital/oikos_api#8]
Se realizarán pruebas sobre las peticiones Post, Get, GetAll, Put y Delete de los servicios del api.

**Comment by mariaortiz0401** [comment]
Se adjunta [excel](https://docs.google.com/spreadsheets/d/1pTlbBudQDLZ-T_Nb4bnMGxhB_xQR-5QExBXZkfQ6Dmw/edit#gid=0) donde se llevan registros de las pruebas realizadas.

**Comment by mariaortiz0401** [comment]
Se termina revisión de los servicios versionados : https://docs.google.com/spreadsheets/d/1pTlbBudQDLZ-T_Nb4bnMGxhB_xQR-5QExBXZkfQ6Dmw/edit#gid=0

Quedan pendientes aquellos con los que no se cuenta con datos para probar de forma más acertada. Sin embargo, se propone dejar estos modelos como están en la nueva base de datos, aprovechando que no hay datos que se jalen o se deban migrar.

**Comment by AlaskaRising** [comment]
http://localhost:8081/v1/dependencia/get_dependencias_padres_by_id/66
http://localhost:8081/v1/dependencia/get_dependencias_hijas_by_id/1
http://localhost:8081/v1/dependencia/proyectosPorFacultad/14
http://localhost:8081/v1/dependencia/proyectosPorFacultad/14/PREGRADO
http://localhost:8081/v1/dependencia_padre/ArbolDependencias
http://localhost:8081/v1/dependencia_padre/FacultadesConProyectos
http://localhost:8081/v2/proyecto_curricular/get_all_proyectos_by_facultades
http://localhost:8081/v2/proyecto_curricular/get_all_proyectos_by_facultad_id/14

Se prueban endpoints de las nuevas funciones con base de datos local y se comprueba su funcionamiento. :100:
